config/routes.rb
KumonoMukou::Application.routes.draw do
  resources :places, only: [:index, :show]
  match '/map', to: 'static_pages#map', via: 'get'

  root 'static_pages#home'

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :place

  IMAGE_TYPES = {
    "image/jpeg" => "jpg",
    "image/gif" => "gif",
    "image/png" => "png"
  }

  def extension
    IMAGE_TYPES[content_type]
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_one :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    if params[:format].in?(["jpg", "png", "gif"])
      send_image
    else
      render "show"
    end
  end

  private
    def send_image
      if @place.photo.present?
        send_data @place.photo.data,
          type: @place.photo.content_type,
          disposition: "inline"
      else
        raise NotFound
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def map
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返す。
  def full_title(page_title)                         # メソッド定義
    base_title = "聖地巡礼「雲のむこう、約束の場所」青森編" # 変数に値を割り当てる
    if page_title.empty?                             # 論理値テスト
      base_title                                     # 暗黙の返り値
    else
      "#{base_title} | #{page_title}"                # 文字列の式展開
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
  def place_image_tag(place, options = {})
    if place.photo.present?
      path = place_path(place, format: place.photo.extension)
      link_to(image_tag(path, { alt: place.description }.merge(options)), path)
    else
      ""
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<% provide(:title, '場所の一覧') %>
<h1>場所の一覧</h1>
<table border="1">
  <thead>
    <tr>
      <th>緯度</th>
      <th>経度</th>
      <th>説明</th>
      <th>写真URL</th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
    <tr>
      <td><%= place.latitude %></td>
      <td><%= place.longitude %></td>
      <td><%= link_to place.description, place %></td>
      <td><%= link_to place_url(place, format: place.photo.extension), place_url(place, format: place.photo.extension) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "ホーム", root_path %>

app/views/places/show.html.erb
<% provide(:title, "場所の詳細: #{@place.description}") %>
<h1>場所の詳細: <%= @place.description %></h1>

<table border="1">
  <tr>
    <th>説明</th>
    <td><%= @place.description %></td>
  </tr>
  <tr>
    <th>緯度</th>
    <td><%= @place.latitude %></td>
  </tr>
  <tr>
    <th>経度</th>
    <td><%= @place.longitude %></td>
  </tr>
  <tr>
    <th>写真URL</th>
    <td><%= place_url(@place, format: @place.photo.extension) %></td>
  </tr>
</table>

<p><%= place_image_tag @place, width: 320 %></p>

<%= link_to '場所の一覧へ戻る', places_path %></p>

app/views/static_pages/home.html.erb
<h1>聖地巡礼「雲のむこう、約束の場所」青森編</h1>
<p>
  新海誠監督、映画「雲のむこう、約束の場所」は青森も舞台となっていて、実在の場所が別名で登場します。
  映画で登場した実在の場所と写真を紹介します。
</p>
<p>
  なお、映画は2004年に公開され、写真は2005年に撮影しています。
  その後、景色は変わってしまっていますので、現在の現地の様子とは異なります。
</p>
<ul>
  <li><%= link_to "マップで見る", map_path, data: { no_turbolink: true } %></li>
  <li><%= link_to "場所の一覧を見る", places_path %></li>
</ul>

app/views/static_pages/map.html.erb
<% provide(:title, 'マップ') %>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/js/map-ramble.js"></script>
<div id="map"></div>